# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weouchea',
            field=models.TextField(default='Empty'),
            preserve_default=False,
        ),
    ]
