# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_weouchea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=140)),
                ('Password', models.CharField(max_length=140)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
